### ISSUE TITLE
array types

### ISSUE THREAD

**Issue by ilayshp** [gatgui/SeExprArnold#1]
Hello, thank you for shader development!
Small test in c4dtoa
![seexprarnold_c4dtoa](https://cloud.githubusercontent.com/assets/2669688/8150194/bcdebda6-1301-11e5-88c4-9a3d6a9c00c8.png)

User when make array of vars, will get dynamically n-number values? Developer(in c4dtoa) should make dynamic layout of controls?!
I'm newbie in seexpr and arnold api.

**Comment by gatgui** [comment]
Arnold doesn't have the notion of compound attributes so fparam_name and fparam_value arrays should be sized the same, just as vparam_name/vparam_value.

Each value will be bound to a variable whose name is the value of the corresponding element in the name array. So if you have "myvar" in fparam_name[0], the value will be that of fparam_value[0] and you can retrieve it in the expression using $user::myvar.

In the develop branch, I made the shader less picky about the size of the arrays: if you don't have enough values, the variable will be set to 0 and any extra values will just be ignored (unbound).

Now, on the UI side, I haven't access to C4D so I can't tell you much. On Maya's side, I haven't done anything yet either. The default attribute editor shows 4 arrays that you have to size manually. No very user friendly so I will eventually write a custom attribute editor script to hide those arnold specific details from the user. I would expect you need to do the same in C4D...

That said, if the attribute editor in C4D do not recognize those attributes as being arrays, then it may very will be a limitation or a bug in the current c4dtoa. Whichever case, you should probably contact the Solid Angle guys to fix that.

Cheers,
Gaetan

**Comment by ilayshp** [comment]
Hello Gaetan
Thank you for answer and tips. SA made c4dapi to extend arnold extensions to c4d gui.
I compile your solution without c4dapi injections. If use such, i think to use userdata > https://support.solidangle.com/display/AFCUG/User+Data >> $user::myvar

Thanks,
Ilay

Sorry for rude form of my issues and my English

**Comment by gatgui** [comment]
Sorry, I should have read myself twice before posting:

Variables specified using the fparam_name/fparam_value and vparam_name/vparam_value on the seexpr shader itself are accessed using $varname directly, while $user::varname is to access attributes attached to the shape being shaded (i.e. that you would normally access via the User Data shader)

**Comment by ilayshp** [comment]
Thank you!
